<?xml version="1.0" encoding="utf-8"?><Database Name="db_info" Class="InfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-A1PIAMK;Initial Catalog=db_info;Persist Security Info=True;User ID=sa" SettingsObjectName="Info.DAL.Properties.Settings" SettingsPropertyName="db_infoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="id_Categoria" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_Categoria" Member="Descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Produto" Member="Produtos" ThisKey="Codigo" OtherKey="CodigoCategoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Produtos" Member="Produtos">
    <Type Name="Produto">
      <Column Name="id_Produto" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_Produto" Member="Descricao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="vl_Valor" Member="Valor" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_Categoria" Member="CodigoCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Produto_ItemVenda" Member="ItemVendas" ThisKey="Codigo" OtherKey="CodigoProduto" Type="ItemVenda" />
      <Association Name="Categoria_Produto" Member="Categoria" ThisKey="CodigoCategoria" OtherKey="Codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Pessoa" Member="Pessoas">
    <Type Name="Pessoa">
      <Column Name="id_Pessoa" Member="CodigoPessoa" Storage="_id_Pessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_Email" Member="Email" Storage="_ds_Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="nm_Nome" Member="Nome" Storage="_nm_Nome" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="no_Telefone" Member="Telefone" Storage="_no_Telefone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Pessoa_PessoaFisica" Member="tbl_Pessoa_Fisica" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="PessoaFisica" Cardinality="One" />
      <Association Name="Pessoa_PessoaJuridica" Member="tbl_Pessoa_Juridica" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="PessoaJuridica" Cardinality="One" />
      <Association Name="Pessoa_Usuario" Member="tbl_Usuario" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Usuario" Cardinality="One" />
      <Association Name="Pessoa_Venda" Member="Vendas" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Venda" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Pessoa_Fisica" Member="PessoaFisicas">
    <Type Name="PessoaFisica">
      <Column Name="id_Pessoa" Member="CodigoPessoa" Storage="_id_Pessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RG" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Nascimento" Member="DataNascimento" Storage="_dt_Nascimento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nm_Pai" Member="NomePai" Storage="_nm_Pai" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="nm_Mae" Member="NomeMae" Storage="_nm_Mae" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Pessoa_PessoaFisica" Member="Pessoa" Storage="_tbl_Pessoa" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Pessoa_Juridica" Member="PessoaJuridicas">
    <Type Name="PessoaJuridica">
      <Column Name="id_pessoa" Member="CodigoPessoa" Storage="_id_pessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Inscricao" Member="InscricaoEstadual" Storage="_Inscricao" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="razao_Social" Member="RazaoSocial" Storage="_razao_Social" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Pessoa_PessoaJuridica" Member="Pessoa" Storage="_tbl_Pessoa" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id_Pessoa" Member="CodigoPessoa" Storage="_id_Pessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Usuario" Member="NomeUsuario" Storage="_Usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Senha" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pessoa_Usuario" Member="Pessoa" Storage="_tbl_Pessoa" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ItensVenda" Member="ItemVendas">
    <Type Name="ItemVenda">
      <Column Name="qt_Quantidade" Member="Quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_Produto" Member="CodigoProduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_Venda" Member="CodigoVenda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vl_Valor" Member="Valor" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_Item" Member="CodigoItem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Produto_ItemVenda" Member="Produto" ThisKey="CodigoProduto" OtherKey="Codigo" Type="Produto" IsForeignKey="true" />
      <Association Name="Venda_ItemVenda" Member="Venda" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="Venda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Venda" Member="Vendas">
    <Type Name="Venda">
      <Column Name="id_Venda" Member="CodigoVenda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vl_Valor" Member="Valor" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="dc_Desconto" Member="Desconto" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="vl_ValorPago" Member="ValorPago" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_Pessoa" Member="CodigoPessoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Venda_ItemVenda" Member="ItemVendas" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="ItemVenda" />
      <Association Name="Venda_tbl_ContasReceber" Member="ContaARecebers" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="ContaAReceber" />
      <Association Name="Pessoa_Venda" Member="Pessoa" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ContasReceber" Member="ContaARecebers">
    <Type Name="ContaAReceber">
      <Column Name="id_Conta" Member="CodigoConta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dt_Compra" Member="DataCompra" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dt_Vencimento" Member="DataVencimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dt_Pagamento" Member="DataPagamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_Venda" Member="CodigoVenda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_Status" Member="CodigoStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Venda_tbl_ContasReceber" Member="Venda" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="Venda" IsForeignKey="true" />
      <Association Name="tbl_StatusPagamento_tbl_ContasReceber" Member="StatusDePagamento" ThisKey="CodigoStatus" OtherKey="CodigoStatus" Type="StatusDePagamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_StatusPagamento" Member="StatusDePagamentos">
    <Type Name="StatusDePagamento">
      <Column Name="id_Status" Member="CodigoStatus" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_Status" Member="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_StatusPagamento_tbl_ContasReceber" Member="ContaARecebers" ThisKey="CodigoStatus" OtherKey="CodigoStatus" Type="ContaAReceber" />
    </Type>
  </Table>
</Database>