#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Info.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_info")]
	public partial class InfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertPessoa(Pessoa instance);
    partial void UpdatePessoa(Pessoa instance);
    partial void DeletePessoa(Pessoa instance);
    partial void InsertPessoaFisica(PessoaFisica instance);
    partial void UpdatePessoaFisica(PessoaFisica instance);
    partial void DeletePessoaFisica(PessoaFisica instance);
    partial void InsertPessoaJuridica(PessoaJuridica instance);
    partial void UpdatePessoaJuridica(PessoaJuridica instance);
    partial void DeletePessoaJuridica(PessoaJuridica instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertItemVenda(ItemVenda instance);
    partial void UpdateItemVenda(ItemVenda instance);
    partial void DeleteItemVenda(ItemVenda instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    partial void InsertContaAReceber(ContaAReceber instance);
    partial void UpdateContaAReceber(ContaAReceber instance);
    partial void DeleteContaAReceber(ContaAReceber instance);
    partial void InsertStatusDePagamento(StatusDePagamento instance);
    partial void UpdateStatusDePagamento(StatusDePagamento instance);
    partial void DeleteStatusDePagamento(StatusDePagamento instance);
    #endregion
		
		public InfoDataContext() : 
				base(global::Info.DAL.Properties.Settings.Default.db_infoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Pessoa> Pessoas
		{
			get
			{
				return this.GetTable<Pessoa>();
			}
		}
		
		public System.Data.Linq.Table<PessoaFisica> PessoaFisicas
		{
			get
			{
				return this.GetTable<PessoaFisica>();
			}
		}
		
		public System.Data.Linq.Table<PessoaJuridica> PessoaJuridicas
		{
			get
			{
				return this.GetTable<PessoaJuridica>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<ItemVenda> ItemVendas
		{
			get
			{
				return this.GetTable<ItemVenda>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Vendas
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
		
		public System.Data.Linq.Table<ContaAReceber> ContaAReceber
		{
			get
			{
				return this.GetTable<ContaAReceber>();
			}
		}
		
		public System.Data.Linq.Table<StatusDePagamento> StatusDePagamentos
		{
			get
			{
				return this.GetTable<StatusDePagamento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Categorias")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private EntitySet<Produto> _Produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Produtos = new EntitySet<Produto>(new Action<Produto>(this.attach_Produtos), new Action<Produto>(this.detach_Produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Categoria", Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ds_Categoria", Storage="_Descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Produtos", ThisKey="Codigo", OtherKey="CodigoCategoria")]
		public EntitySet<Produto> Produtos
		{
			get
			{
				return this._Produtos;
			}
			set
			{
				this._Produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produtos(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Produtos(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Produtos")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<int> _CodigoCategoria;
		
		private EntitySet<ItemVenda> _ItemVendas;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnCodigoCategoriaChanging(System.Nullable<int> value);
    partial void OnCodigoCategoriaChanged();
    #endregion
		
		public Produto()
		{
			this._ItemVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_ItemVendas), new Action<ItemVenda>(this.detach_ItemVendas));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Produto", Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ds_Produto", Storage="_Descricao", DbType="VarChar(80)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vl_Valor", Storage="_Valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Categoria", Storage="_CodigoCategoria", DbType="Int")]
		public System.Nullable<int> CodigoCategoria
		{
			get
			{
				return this._CodigoCategoria;
			}
			set
			{
				if ((this._CodigoCategoria != value))
				{
					this.OnCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCategoria = value;
					this.SendPropertyChanged("CodigoCategoria");
					this.OnCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItemVenda", Storage="_ItemVendas", ThisKey="Codigo", OtherKey="CodigoProduto")]
		public EntitySet<ItemVenda> ItemVendas
		{
			get
			{
				return this._ItemVendas;
			}
			set
			{
				this._ItemVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Categoria", ThisKey="CodigoCategoria", OtherKey="Codigo", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Produtos.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Produtos.Add(this);
						this._CodigoCategoria = value.Codigo;
					}
					else
					{
						this._CodigoCategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Pessoa")]
	public partial class Pessoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Pessoa;
		
		private string _ds_Email;
		
		private string _nm_Nome;
		
		private string _no_Telefone;
		
		private EntityRef<PessoaFisica> _tbl_Pessoa_Fisica;
		
		private EntityRef<PessoaJuridica> _tbl_Pessoa_Juridica;
		
		private EntityRef<Usuario> _tbl_Usuario;
		
		private EntitySet<Venda> _Vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    #endregion
		
		public Pessoa()
		{
			this._tbl_Pessoa_Fisica = default(EntityRef<PessoaFisica>);
			this._tbl_Pessoa_Juridica = default(EntityRef<PessoaJuridica>);
			this._tbl_Usuario = default(EntityRef<Usuario>);
			this._Vendas = new EntitySet<Venda>(new Action<Venda>(this.attach_Vendas), new Action<Venda>(this.detach_Vendas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Pessoa", Storage="_id_Pessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._id_Pessoa;
			}
			set
			{
				if ((this._id_Pessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._id_Pessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ds_Email", Storage="_ds_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._ds_Email;
			}
			set
			{
				if ((this._ds_Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._ds_Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nm_Nome", Storage="_nm_Nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._nm_Nome;
			}
			set
			{
				if ((this._nm_Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._nm_Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="no_Telefone", Storage="_no_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._no_Telefone;
			}
			set
			{
				if ((this._no_Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._no_Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_PessoaFisica", Storage="_tbl_Pessoa_Fisica", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsUnique=true, IsForeignKey=false)]
		public PessoaFisica tbl_Pessoa_Fisica
		{
			get
			{
				return this._tbl_Pessoa_Fisica.Entity;
			}
			set
			{
				PessoaFisica previousValue = this._tbl_Pessoa_Fisica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pessoa_Fisica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pessoa_Fisica.Entity = null;
						previousValue.Pessoa = null;
					}
					this._tbl_Pessoa_Fisica.Entity = value;
					if ((value != null))
					{
						value.Pessoa = this;
					}
					this.SendPropertyChanged("tbl_Pessoa_Fisica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_PessoaJuridica", Storage="_tbl_Pessoa_Juridica", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsUnique=true, IsForeignKey=false)]
		public PessoaJuridica tbl_Pessoa_Juridica
		{
			get
			{
				return this._tbl_Pessoa_Juridica.Entity;
			}
			set
			{
				PessoaJuridica previousValue = this._tbl_Pessoa_Juridica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pessoa_Juridica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pessoa_Juridica.Entity = null;
						previousValue.Pessoa = null;
					}
					this._tbl_Pessoa_Juridica.Entity = value;
					if ((value != null))
					{
						value.Pessoa = this;
					}
					this.SendPropertyChanged("tbl_Pessoa_Juridica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_Usuario", Storage="_tbl_Usuario", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsUnique=true, IsForeignKey=false)]
		public Usuario tbl_Usuario
		{
			get
			{
				return this._tbl_Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._tbl_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Usuario.Entity = null;
						previousValue.Pessoa = null;
					}
					this._tbl_Usuario.Entity = value;
					if ((value != null))
					{
						value.Pessoa = this;
					}
					this.SendPropertyChanged("tbl_Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_Venda", Storage="_Vendas", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa")]
		public EntitySet<Venda> Vendas
		{
			get
			{
				return this._Vendas;
			}
			set
			{
				this._Vendas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vendas(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Pessoa = this;
		}
		
		private void detach_Vendas(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Pessoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Pessoa_Fisica")]
	public partial class PessoaFisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Pessoa;
		
		private string _CPF;
		
		private string _RG;
		
		private System.Nullable<System.DateTime> _dt_Nascimento;
		
		private string _nm_Pai;
		
		private string _nm_Mae;
		
		private EntityRef<Pessoa> _tbl_Pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnDataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascimentoChanged();
    partial void OnNomePaiChanging(string value);
    partial void OnNomePaiChanged();
    partial void OnNomeMaeChanging(string value);
    partial void OnNomeMaeChanged();
    #endregion
		
		public PessoaFisica()
		{
			this._tbl_Pessoa = default(EntityRef<Pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Pessoa", Storage="_id_Pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._id_Pessoa;
			}
			set
			{
				if ((this._id_Pessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._id_Pessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dt_Nascimento", Storage="_dt_Nascimento", DbType="Date")]
		public System.Nullable<System.DateTime> DataNascimento
		{
			get
			{
				return this._dt_Nascimento;
			}
			set
			{
				if ((this._dt_Nascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._dt_Nascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nm_Pai", Storage="_nm_Pai", DbType="VarChar(200)")]
		public string NomePai
		{
			get
			{
				return this._nm_Pai;
			}
			set
			{
				if ((this._nm_Pai != value))
				{
					this.OnNomePaiChanging(value);
					this.SendPropertyChanging();
					this._nm_Pai = value;
					this.SendPropertyChanged("NomePai");
					this.OnNomePaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nm_Mae", Storage="_nm_Mae", DbType="VarChar(200)")]
		public string NomeMae
		{
			get
			{
				return this._nm_Mae;
			}
			set
			{
				if ((this._nm_Mae != value))
				{
					this.OnNomeMaeChanging(value);
					this.SendPropertyChanging();
					this._nm_Mae = value;
					this.SendPropertyChanged("NomeMae");
					this.OnNomeMaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_PessoaFisica", Storage="_tbl_Pessoa", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoa Pessoa
		{
			get
			{
				return this._tbl_Pessoa.Entity;
			}
			set
			{
				Pessoa previousValue = this._tbl_Pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pessoa.Entity = null;
						previousValue.tbl_Pessoa_Fisica = null;
					}
					this._tbl_Pessoa.Entity = value;
					if ((value != null))
					{
						value.tbl_Pessoa_Fisica = this;
						this._id_Pessoa = value.CodigoPessoa;
					}
					else
					{
						this._id_Pessoa = default(int);
					}
					this.SendPropertyChanged("Pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Pessoa_Juridica")]
	public partial class PessoaJuridica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pessoa;
		
		private string _CNPJ;
		
		private string _Inscricao;
		
		private string _razao_Social;
		
		private EntityRef<Pessoa> _tbl_Pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    partial void OnInscricaoEstadualChanging(string value);
    partial void OnInscricaoEstadualChanged();
    partial void OnRazaoSocialChanging(string value);
    partial void OnRazaoSocialChanged();
    #endregion
		
		public PessoaJuridica()
		{
			this._tbl_Pessoa = default(EntityRef<Pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Inscricao", Storage="_Inscricao", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string InscricaoEstadual
		{
			get
			{
				return this._Inscricao;
			}
			set
			{
				if ((this._Inscricao != value))
				{
					this.OnInscricaoEstadualChanging(value);
					this.SendPropertyChanging();
					this._Inscricao = value;
					this.SendPropertyChanged("InscricaoEstadual");
					this.OnInscricaoEstadualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="razao_Social", Storage="_razao_Social", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string RazaoSocial
		{
			get
			{
				return this._razao_Social;
			}
			set
			{
				if ((this._razao_Social != value))
				{
					this.OnRazaoSocialChanging(value);
					this.SendPropertyChanging();
					this._razao_Social = value;
					this.SendPropertyChanged("RazaoSocial");
					this.OnRazaoSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_PessoaJuridica", Storage="_tbl_Pessoa", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoa Pessoa
		{
			get
			{
				return this._tbl_Pessoa.Entity;
			}
			set
			{
				Pessoa previousValue = this._tbl_Pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pessoa.Entity = null;
						previousValue.tbl_Pessoa_Juridica = null;
					}
					this._tbl_Pessoa.Entity = value;
					if ((value != null))
					{
						value.tbl_Pessoa_Juridica = this;
						this._id_pessoa = value.CodigoPessoa;
					}
					else
					{
						this._id_pessoa = default(int);
					}
					this.SendPropertyChanged("Pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Pessoa;
		
		private string _Usuario;
		
		private string _Senha;
		
		private EntityRef<Pessoa> _tbl_Pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    partial void OnNomeUsuarioChanging(string value);
    partial void OnNomeUsuarioChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    #endregion
		
		public Usuario()
		{
			this._tbl_Pessoa = default(EntityRef<Pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Pessoa", Storage="_id_Pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._id_Pessoa;
			}
			set
			{
				if ((this._id_Pessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._id_Pessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeUsuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnNomeUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("NomeUsuario");
					this.OnNomeUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_Usuario", Storage="_tbl_Pessoa", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoa Pessoa
		{
			get
			{
				return this._tbl_Pessoa.Entity;
			}
			set
			{
				Pessoa previousValue = this._tbl_Pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pessoa.Entity = null;
						previousValue.tbl_Usuario = null;
					}
					this._tbl_Pessoa.Entity = value;
					if ((value != null))
					{
						value.tbl_Usuario = this;
						this._id_Pessoa = value.CodigoPessoa;
					}
					else
					{
						this._id_Pessoa = default(int);
					}
					this.SendPropertyChanged("Pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ItensVenda")]
	public partial class ItemVenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Quantidade;
		
		private int _CodigoProduto;
		
		private int _CodigoVenda;
		
		private decimal _Valor;
		
		private int _CodigoItem;
		
		private EntityRef<Produto> _Produto;
		
		private EntityRef<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnCodigoItemChanging(int value);
    partial void OnCodigoItemChanged();
    #endregion
		
		public ItemVenda()
		{
			this._Produto = default(EntityRef<Produto>);
			this._Venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="qt_Quantidade", Storage="_Quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Produto", Storage="_CodigoProduto", DbType="Int NOT NULL")]
		public int CodigoProduto
		{
			get
			{
				return this._CodigoProduto;
			}
			set
			{
				if ((this._CodigoProduto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProduto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Venda", Storage="_CodigoVenda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vl_Valor", Storage="_Valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Item", Storage="_CodigoItem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoItem
		{
			get
			{
				return this._CodigoItem;
			}
			set
			{
				if ((this._CodigoItem != value))
				{
					this.OnCodigoItemChanging(value);
					this.SendPropertyChanging();
					this._CodigoItem = value;
					this.SendPropertyChanged("CodigoItem");
					this.OnCodigoItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItemVenda", Storage="_Produto", ThisKey="CodigoProduto", OtherKey="Codigo", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.ItemVendas.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.ItemVendas.Add(this);
						this._CodigoProduto = value.Codigo;
					}
					else
					{
						this._CodigoProduto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItemVenda", Storage="_Venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.ItemVendas.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.ItemVendas.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoVenda;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<decimal> _Desconto;
		
		private System.Nullable<decimal> _ValorPago;
		
		private System.Nullable<int> _CodigoPessoa;
		
		private EntitySet<ItemVenda> _ItemVendas;
		
		private EntitySet<ContaAReceber> _ContaAReceber;
		
		private EntityRef<Pessoa> _Pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnValorPagoChanging(System.Nullable<decimal> value);
    partial void OnValorPagoChanged();
    partial void OnCodigoPessoaChanging(System.Nullable<int> value);
    partial void OnCodigoPessoaChanged();
    #endregion
		
		public Venda()
		{
			this._ItemVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_ItemVendas), new Action<ItemVenda>(this.detach_ItemVendas));
			this._ContaAReceber = new EntitySet<ContaAReceber>(new Action<ContaAReceber>(this.attach_ContaAReceber), new Action<ContaAReceber>(this.detach_ContaAReceber));
			this._Pessoa = default(EntityRef<Pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Venda", Storage="_CodigoVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vl_Valor", Storage="_Valor", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dc_Desconto", Storage="_Desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._Desconto;
			}
			set
			{
				if ((this._Desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._Desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vl_ValorPago", Storage="_ValorPago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorPago
		{
			get
			{
				return this._ValorPago;
			}
			set
			{
				if ((this._ValorPago != value))
				{
					this.OnValorPagoChanging(value);
					this.SendPropertyChanging();
					this._ValorPago = value;
					this.SendPropertyChanged("ValorPago");
					this.OnValorPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Pessoa", Storage="_CodigoPessoa", DbType="Int")]
		public System.Nullable<int> CodigoPessoa
		{
			get
			{
				return this._CodigoPessoa;
			}
			set
			{
				if ((this._CodigoPessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._CodigoPessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItemVenda", Storage="_ItemVendas", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ItemVenda> ItemVendas
		{
			get
			{
				return this._ItemVendas;
			}
			set
			{
				this._ItemVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_tbl_ContasReceber", Storage="_ContaAReceber", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ContaAReceber> ContaAReceber
		{
			get
			{
				return this._ContaAReceber;
			}
			set
			{
				this._ContaAReceber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoa_Venda", Storage="_Pessoa", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoa Pessoa
		{
			get
			{
				return this._Pessoa.Entity;
			}
			set
			{
				Pessoa previousValue = this._Pessoa.Entity;
				if (((previousValue != value) 
							|| (this._Pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pessoa.Entity = null;
						previousValue.Vendas.Remove(this);
					}
					this._Pessoa.Entity = value;
					if ((value != null))
					{
						value.Vendas.Add(this);
						this._CodigoPessoa = value.CodigoPessoa;
					}
					else
					{
						this._CodigoPessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
		
		private void attach_ContaAReceber(ContaAReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_ContaAReceber(ContaAReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ContasReceber")]
	public partial class ContaAReceber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoConta;
		
		private System.DateTime _DataCompra;
		
		private System.DateTime _DataVencimento;
		
		private System.Nullable<System.DateTime> _DataPagamento;
		
		private int _CodigoVenda;
		
		private int _CodigoStatus;
		
		private EntityRef<Venda> _Venda;
		
		private EntityRef<StatusDePagamento> _StatusDePagamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoContaChanging(int value);
    partial void OnCodigoContaChanged();
    partial void OnDataCompraChanging(System.DateTime value);
    partial void OnDataCompraChanged();
    partial void OnDataVencimentoChanging(System.DateTime value);
    partial void OnDataVencimentoChanged();
    partial void OnDataPagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPagamentoChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnCodigoStatusChanging(int value);
    partial void OnCodigoStatusChanged();
    #endregion
		
		public ContaAReceber()
		{
			this._Venda = default(EntityRef<Venda>);
			this._StatusDePagamento = default(EntityRef<StatusDePagamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Conta", Storage="_CodigoConta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoConta
		{
			get
			{
				return this._CodigoConta;
			}
			set
			{
				if ((this._CodigoConta != value))
				{
					this.OnCodigoContaChanging(value);
					this.SendPropertyChanging();
					this._CodigoConta = value;
					this.SendPropertyChanged("CodigoConta");
					this.OnCodigoContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dt_Compra", Storage="_DataCompra", DbType="Date NOT NULL")]
		public System.DateTime DataCompra
		{
			get
			{
				return this._DataCompra;
			}
			set
			{
				if ((this._DataCompra != value))
				{
					this.OnDataCompraChanging(value);
					this.SendPropertyChanging();
					this._DataCompra = value;
					this.SendPropertyChanged("DataCompra");
					this.OnDataCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dt_Vencimento", Storage="_DataVencimento", DbType="Date NOT NULL")]
		public System.DateTime DataVencimento
		{
			get
			{
				return this._DataVencimento;
			}
			set
			{
				if ((this._DataVencimento != value))
				{
					this.OnDataVencimentoChanging(value);
					this.SendPropertyChanging();
					this._DataVencimento = value;
					this.SendPropertyChanged("DataVencimento");
					this.OnDataVencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dt_Pagamento", Storage="_DataPagamento", DbType="Date")]
		public System.Nullable<System.DateTime> DataPagamento
		{
			get
			{
				return this._DataPagamento;
			}
			set
			{
				if ((this._DataPagamento != value))
				{
					this.OnDataPagamentoChanging(value);
					this.SendPropertyChanging();
					this._DataPagamento = value;
					this.SendPropertyChanged("DataPagamento");
					this.OnDataPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Venda", Storage="_CodigoVenda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Status", Storage="_CodigoStatus", DbType="Int NOT NULL")]
		public int CodigoStatus
		{
			get
			{
				return this._CodigoStatus;
			}
			set
			{
				if ((this._CodigoStatus != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CodigoStatus = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_tbl_ContasReceber", Storage="_Venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.ContaAReceber.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.ContaAReceber.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_StatusPagamento_tbl_ContasReceber", Storage="_StatusDePagamento", ThisKey="CodigoStatus", OtherKey="CodigoStatus", IsForeignKey=true)]
		public StatusDePagamento StatusDePagamento
		{
			get
			{
				return this._StatusDePagamento.Entity;
			}
			set
			{
				StatusDePagamento previousValue = this._StatusDePagamento.Entity;
				if (((previousValue != value) 
							|| (this._StatusDePagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StatusDePagamento.Entity = null;
						previousValue.ContaAReceber.Remove(this);
					}
					this._StatusDePagamento.Entity = value;
					if ((value != null))
					{
						value.ContaAReceber.Add(this);
						this._CodigoStatus = value.CodigoStatus;
					}
					else
					{
						this._CodigoStatus = default(int);
					}
					this.SendPropertyChanged("StatusDePagamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_StatusPagamento")]
	public partial class StatusDePagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoStatus;
		
		private string _Status;
		
		private EntitySet<ContaAReceber> _ContaAReceber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoStatusChanging(int value);
    partial void OnCodigoStatusChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public StatusDePagamento()
		{
			this._ContaAReceber = new EntitySet<ContaAReceber>(new Action<ContaAReceber>(this.attach_ContaAReceber), new Action<ContaAReceber>(this.detach_ContaAReceber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Status", Storage="_CodigoStatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoStatus
		{
			get
			{
				return this._CodigoStatus;
			}
			set
			{
				if ((this._CodigoStatus != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CodigoStatus = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ds_Status", Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_StatusPagamento_tbl_ContasReceber", Storage="_ContaAReceber", ThisKey="CodigoStatus", OtherKey="CodigoStatus")]
		public EntitySet<ContaAReceber> ContaAReceber
		{
			get
			{
				return this._ContaAReceber;
			}
			set
			{
				this._ContaAReceber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContaAReceber(ContaAReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusDePagamento = this;
		}
		
		private void detach_ContaAReceber(ContaAReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusDePagamento = null;
		}
	}
}
#pragma warning restore 1591
